// Product and category data for SukalMart

export const categories = [
  {
    name: "Hair Care",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/category/A_collection_of_hair_care_products_displayed_in_a_sleek_salon-inspired_setting_15-02-2025_at_23-21-09.webp",
  },
  {
    name: "Body & Shower",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/category/https___hypebeast.com_wp-content_blogs.dir_6_files_2019_10_luxury-bath-shower-products-soap-body-scrub-shampoo-aesop-glossier-chanel-00.avif",
  },
  {
    name: "Soap & Deodorants",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/category/JBX_Soap_Deo_Mix_Pack.webp",
  },
  {
    name: "Skin Care",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/category/168838_00_2x.webp",
  },
  {
    name: "Oral & Misc",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/category/mouthwash-other-oral-hygiene-products-colored-table-top-view-with-copy-space-flat-lay-dental-hygiene-oral-care-products-space-text-light-background-concept_79075-26657.avif",
  },
  // {
  //   name: "Accessories",
  //   image: "/shop6.png",
  // },
];

export const bestSellers = [
  {
    id: 101,
    name: "Hydrating Face Wash",
    category: "Skin Care",
    price: "₹599",
    originalPrice: "₹799",
    image: "/skin1.jpg",
    badge: "#1",
  },
  {
    id: 102,
    name: "Nourishing Body Lotion",
    category: "Body & Shower",
    price: "₹349",
    originalPrice: "₹499",
    image: "/bodywah.jpg",
    badge: "#2",
  },
  {
    id: 103,
    name: "Herbal Anti-Dandruff Shampoo",
    category: "Hair Care",
    price: "₹299",
    originalPrice: "₹399",
    image: "/haircare1.jpg",
    badge: "#3",
  },
  {
    id: 104,
    name: "Long-Lasting Deodorant Roll-On",
    category: "Soap & Deodorants",
    price: "₹199",
    originalPrice: "₹249",
    image: "/soap.png",
  },
];

export const featuredProducts = [
  {
    id: 1,
    name: "Glow & Hydrate Face Serum",
    category: "Skincare",
    rating: 4.5,
    description:
      "Advanced hydrating serum with hyaluronic acid and vitamin C for radiant, glowing skin. Suitable for all skin types.",
    price: "₹899",
    originalPrice: "₹1,099",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
  },
  {
    id: 2,
    name: "Luxury Beauty Collection Set",
    category: "Beauty Essentials",
    rating: 4.5,
    description:
      "Complete beauty routine set including cleanser, toner, moisturizer, and makeup essentials for flawless skin.",
    price: "₹2,499",
    originalPrice: "₹3,199",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
  },
];

// Full catalog used on /products page (exported for search suggestions)
export const catalogProducts = [
  // Hair Care products
  {
    id: "hc1",
    name: "Professional Hair Shampoo",
    type: "Hair Care",
    price: 899,
    originalPrice: 1099,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 18,
  },
  {
    id: "hc2",
    name: "Nourishing Hair Conditioner",
    type: "Hair Care",
    price: 799,
    originalPrice: 999,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 20,
  },
  {
    id: "hc3",
    name: "Anti-Dandruff Treatment",
    type: "Hair Care",
    price: 699,
    originalPrice: 899,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 22,
  },
  {
    id: "hc4",
    name: "Hair Growth Serum",
    type: "Hair Care",
    price: 1299,
    originalPrice: 1599,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 19,
  },
  // Soap & Deodorants products
  {
    id: "sd1",
    name: "Natural Handmade Soap",
    type: "Soap & Deodorants",
    price: 299,
    originalPrice: 399,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "sd2",
    name: "Antibacterial Body Wash",
    type: "Soap & Deodorants",
    price: 449,
    originalPrice: 599,
    image: "/soap2.jpg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "sd3",
    name: "Long-lasting Deodorant",
    type: "Soap & Deodorants",
    price: 199,
    originalPrice: 299,
    image: "/soap3.jpg",
    category: "Soap & Deodorants",
    discount: 33,
  },
  {
    id: "sd4",
    name: "Moisturizing Bath Soap",
    type: "Soap & Deodorants",
    price: 349,
    originalPrice: 449,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 22,
  },
  // Skin Care products
  {
    id: "sc1",
    name: "Hydrating Face Moisturizer",
    type: "Skin Care",
    price: 899,
    originalPrice: 1099,
    image: "/skin1.jpg",
    category: "Skin Care",
    discount: 18,
  },
  {
    id: "sc2",
    name: "Vitamin C Brightening Serum",
    type: "Skin Care",
    price: 1299,
    originalPrice: 1599,
    image: "/skin2.jpg",
    category: "Skin Care",
    discount: 19,
  },
  {
    id: "sc3",
    name: "Gentle Facial Cleanser",
    type: "Skin Care",
    price: 599,
    originalPrice: 799,
    image: "/skin3.jpg",
    category: "Skin Care",
    discount: 25,
  },
  {
    id: "sc4",
    name: "Anti-Aging Night Cream",
    type: "Skin Care",
    price: 1499,
    originalPrice: 1899,
    image: "/skin5.jpg",
    category: "Skin Care",
    discount: 21,
  },
  // Oral Care products
  {
    id: "oc1",
    name: "Whitening Toothpaste",
    type: "Oral Care",
    price: 199,
    originalPrice: 299,
    image: "/tooth1.jpg",
    category: "Oral Care",
    discount: 33,
  },
  {
    id: "oc2",
    name: "Electric Toothbrush",
    type: "Oral Care",
    price: 899,
    originalPrice: 1199,
    image: "/tooth2.jpg",
    category: "Oral Care",
    discount: 25,
  },
  {
    id: "oc3",
    name: "Mouthwash Fresh Mint",
    type: "Oral Care",
    price: 299,
    originalPrice: 399,
    image: "/tooth3.jpg",
    category: "Oral Care",
    discount: 25,
  },
  {
    id: "oc4",
    name: "Dental Floss Set",
    type: "Oral Care",
    price: 149,
    originalPrice: 249,
    image: "/tooth4.jpg",
    category: "Oral Care",
    discount: 40,
  },
  // Oral & Misc products (same as Oral Care but with different type)
  {
    id: "oc1_misc",
    name: "Whitening Toothpaste",
    type: "Oral & Misc",
    price: 199,
    originalPrice: 299,
    image: "/tooth1.jpg",
    category: "Oral & Misc",
    discount: 33,
  },
  {
    id: "oc2_misc",
    name: "Electric Toothbrush",
    type: "Oral & Misc",
    price: 899,
    originalPrice: 1199,
    image: "/tooth2.jpg",
    category: "Oral & Misc",
    discount: 25,
  },
  {
    id: "oc3_misc",
    name: "Mouthwash Fresh Mint",
    type: "Oral & Misc",
    price: 299,
    originalPrice: 399,
    image: "/tooth3.jpg",
    category: "Oral & Misc",
    discount: 25,
  },
  {
    id: "oc4_misc",
    name: "Dental Floss Set",
    type: "Oral & Misc",
    price: 149,
    originalPrice: 249,
    image: "/tooth4.jpg",
    category: "Oral & Misc",
    discount: 40,
  },
  // Original catalog products
  {
    id: "1",
    name: "Glow & Hydrate Face Serum",
    type: "Skincare",
    price: 899,
    originalPrice: 1099,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 18,
  },
  {
    id: "2",
    name: "Luxury Beauty Collection Set",
    type: "Beauty Essentials",
    price: 2499,
    originalPrice: 3199,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Beauty Essentials",
    discount: 22,
  },
  {
    id: "3",
    name: "Anti-Aging Night Cream",
    type: "Anti-Aging",
    price: 1299,
    originalPrice: 1599,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Anti-Aging",
    discount: 19,
  },
  {
    id: "4",
    name: "Vitamin C Brightening Serum",
    type: "Skincare",
    price: 799,
    originalPrice: 999,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Skincare",
    discount: 20,
  },
  {
    id: "5",
    name: "Hyaluronic Acid Moisturizer",
    type: "Skincare",
    price: 699,
    originalPrice: 899,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 22,
  },
  {
    id: "6",
    name: "Retinol Eye Cream",
    type: "Anti-Aging",
    price: 999,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Anti-Aging",
    discount: 23,
  },
  {
    id: "7",
    name: "Gentle Facial Cleanser",
    type: "Skincare",
    price: 599,
    originalPrice: 799,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 25,
  },
  {
    id: "8",
    name: "SPF 50 Sunscreen",
    type: "Skincare",
    price: 899,
    originalPrice: 1199,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Skincare",
    discount: 25,
  },
  // New Launches Products
  {
    id: "13",
    name: "THE ANSWER Super Shampoo",
    type: "Hair Care",
    price: 1299,
    originalPrice: 1599,
    image: "/newlaunch1.jpg",
    category: "Hair Care",
    discount: 19,
  },
  {
    id: "14",
    name: "NEWEST Onion Protein Shampoo",
    type: "Hair Care",
    price: 899,
    originalPrice: 1199,
    image: "/newlaunch2.jpg",
    category: "Hair Care",
    discount: 25,
  },
  {
    id: "15",
    name: "FLAKES Anti-Dandruff Shampoo",
    type: "Hair Care",
    price: 699,
    originalPrice: 899,
    image: "/newlaunch3.jpg",
    category: "Hair Care",
    discount: 22,
  },
  {
    id: "16",
    name: "REDKEN Anti-Dandruff Shampoo",
    type: "Hair Care",
    price: 1499,
    originalPrice: 1899,
    image: "/newlaunch4.jpeg",
    category: "Hair Care",
    discount: 21,
  },
  // EngineeredBy7Hz Products
  {
    id: "17",
    name: "Glow & Hydrate Face Serum",
    type: "Skincare",
    price: 899,
    originalPrice: 1099,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 18,
  },
  {
    id: "18",
    name: "Luxury Beauty Collection Set",
    type: "Beauty Essentials",
    price: 2499,
    originalPrice: 3199,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Beauty Essentials",
    discount: 22,
  },
  {
    id: "19",
    name: "Anti-Aging Night Cream",
    type: "Anti-Aging",
    price: 1299,
    originalPrice: 1599,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Anti-Aging",
    discount: 19,
  },
  // Best Sellers Products
  {
    id: "20",
    name: "Dove Nutritive Solutions",
    type: "Hair Care",
    price: 1099,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Hair Care",
    discount: 15,
  },
  {
    id: "21",
    name: "Lux Body Wash",
    type: "Body & Shower",
    price: 1099,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Body & Shower",
    discount: 15,
  },
  {
    id: "22",
    name: "Rexona / Sure Deo",
    type: "Soap & Deodorants",
    price: 1899,
    originalPrice: 2099,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Soap & Deodorants",
    discount: 10,
  },
  {
    id: "23",
    name: "Vaseline Body Lotion",
    type: "Skin Care",
    price: 1099,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Skin Care",
    discount: 15,
  },
  // Additional Products Set 1
  {
    id: "24",
    name: "Professional Hair Shampoo",
    type: "Hair Care",
    price: 899,
    originalPrice: 1099,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 18,
  },
  {
    id: "25",
    name: "Natural Handmade Soap",
    type: "Soap & Deodorants",
    price: 299,
    originalPrice: 399,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "26",
    name: "Hydrating Face Moisturizer",
    type: "Skin Care",
    price: 899,
    originalPrice: 1099,
    image: "/skin1.jpg",
    category: "Skin Care",
    discount: 18,
  },
  {
    id: "27",
    name: "Whitening Toothpaste",
    type: "Oral Care",
    price: 199,
    originalPrice: 299,
    image: "/tooth1.jpg",
    category: "Oral Care",
    discount: 33,
  },
  {
    id: "28",
    name: "Nourishing Hair Conditioner",
    type: "Hair Care",
    price: 799,
    originalPrice: 999,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 20,
  },
  {
    id: "29",
    name: "Antibacterial Body Wash",
    type: "Soap & Deodorants",
    price: 449,
    originalPrice: 599,
    image: "/soap2.jpg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "30",
    name: "Vitamin C Brightening Serum",
    type: "Skin Care",
    price: 1299,
    originalPrice: 1599,
    image: "/skin2.jpg",
    category: "Skin Care",
    discount: 19,
  },
  {
    id: "31",
    name: "Electric Toothbrush",
    type: "Oral Care",
    price: 899,
    originalPrice: 1199,
    image: "/tooth2.jpg",
    category: "Oral Care",
    discount: 25,
  },
  // Additional Products Set 2
  {
    id: "32",
    name: "Anti-Dandruff Treatment",
    type: "Hair Care",
    price: 699,
    originalPrice: 899,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 22,
  },
  {
    id: "33",
    name: "Long-lasting Deodorant",
    type: "Soap & Deodorants",
    price: 199,
    originalPrice: 299,
    image: "/soap3.jpg",
    category: "Soap & Deodorants",
    discount: 33,
  },
  {
    id: "34",
    name: "Gentle Facial Cleanser",
    type: "Skin Care",
    price: 599,
    originalPrice: 799,
    image: "/skin3.jpg",
    category: "Skin Care",
    discount: 25,
  },
  {
    id: "35",
    name: "Mouthwash Fresh Mint",
    type: "Oral Care",
    price: 299,
    originalPrice: 399,
    image: "/tooth3.jpg",
    category: "Oral Care",
    discount: 25,
  },
  {
    id: "36",
    name: "Hair Growth Serum",
    type: "Hair Care",
    price: 1299,
    originalPrice: 1599,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 19,
  },
  {
    id: "37",
    name: "Moisturizing Bath Soap",
    type: "Soap & Deodorants",
    price: 349,
    originalPrice: 449,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 22,
  },
  {
    id: "38",
    name: "Anti-Aging Night Cream",
    type: "Skin Care",
    price: 1499,
    originalPrice: 1899,
    image: "/skin5.jpg",
    category: "Skin Care",
    discount: 21,
  },
  {
    id: "39",
    name: "Dental Floss Set",
    type: "Oral Care",
    price: 149,
    originalPrice: 249,
    image: "/tooth4.jpg",
    category: "Oral Care",
    discount: 40,
  },
];

export const serviceBenefits = [
  {
    icon: "/cash1.svg",
    title: "Secured payment",
    alt: "Secured Payment",
  },
  {
    icon: "/cash2.svg",
    title: "Delivery in 3-4 working days",
    alt: "Delivery",
  },
  {
    icon: "/cash3.svg",
    title: "24x7 support",
    alt: "24x7 Support",
  },
  {
    icon: "/cash4.svg",
    title: "Pay on delivery",
    alt: "Pay on Delivery",
  },
];

export const navigationLinks = [
  "Hair Care",
  "Body & Shower",
  "Soap & Deodorants",
  "Skin Care",
  "Oral & Misc",
];
